- name: Debian | Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://sensu.global.ssl.fastly.net/apt/pubkey.gpg
    state: present

    #- debug:
    #var: hostvars[inventory_hostname]

# Add specified repository into sources list.
- apt_repository:
    repo: deb https://sensu.global.ssl.fastly.net/apt {{ ansible_distribution_release }} main
    state: present

- apt:
    name: "sensu"
    state: present

- service:
    name: sensu-client
    enabled: yes

- service:
    name: sensu-client
    state: started
