kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pd-cassandra-volume-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
