# deployment.yml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: scala-app
  labels:
    app: scala-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scala-app
  template:
    metadata:
      labels:
        app: scala-app
    spec:
      containers:
      - name: scala-app-container
        image: gcr.io/remi-test-241607/scala-app:latest
        imagePullPolicy: Always
        env:
        - name: CASSANDRA_HOST
          value: cassandra.default.svc.cluster.local
        ports:
        - containerPort: 9000
