- name: Setup basic actions on computers at home
  hosts: all

  vars_files:
  - ~/osobiste/dane_aplikacji/remik/ansible_vault.yml

  become: yes
  become_user: root
  tasks:

# setup_common
   - name: Common block that installs Redis binaries, to be used both on Redis and Sentinel hosts
     block:

       - name: Check if port {{ R_PORT }} is open. If it is, let's fail and investigate manually.
         shell: ss -ltpn | grep :{{ R_PORT }} | wc -l
         register: open_redis_port
         changed_when: False

       - debug: msg="{{ open_redis_port.stdout }}"
       
       - name: Fail playbook execution if port {{ R_PORT }} is open
         fail:
           msg: Port {{ R_PORT }} is open. Failing, please investigate manually.
         when: open_redis_port.stdout | int > 0


       - name: Check if port {{ R_SENTINEL_PORT }} is open. If it is, let's fail and investigate manually.
         shell: ss -ltpn | grep :{{ R_SENTINEL_PORT }} | wc -l
         register: open_sentinel_port
         changed_when: False

       - debug: msg="{{ open_sentinel_port.stdout }}"
       
       - name: Fail playbook execution if port {{ R_SENTINEL_PORT }} is open
         fail:
           msg: Port {{ R_SENTINEL_PORT }} is open. Failing, please investigate manually.
         when: open_sentinel_port | int > 0



       - name: Install required packages on Debian
         apt:
           name: tcl
           state: present
         when: ansible_distribution == 'Debian'
         tags:
          - install-os-packages

       - name: Install required packages on Redhat
         yum:
           name: tcl,gcc-c++,gcc,git
           state: present
         when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'OracleLinux'
         tags:
          - install-os-packages
    
       - name: Create redis_compile directory
         file:
           path: ~/redis_compile
           state: directory
         tags:
          - redis-dir
    
       - name: Download redis-6.2.3.tar.gz
         get_url:
           url: https://download.redis.io/releases/redis-6.2.3.tar.gz
           dest: ~/redis_compile/redis-6.2.3.tar.gz
           checksum: md5:15d090d65986bf2dc91223fec8da5627
         tags:
          - redis-download
    
       - name: Extract redis-6.2.3.tar.gz
         unarchive:
           src: ~/redis_compile/redis-6.2.3.tar.gz
           dest: ~/redis_compile
           remote_src: yes
           creates: ~/redis_compile/redis-6.2.3
         tags:
          - redis-extract
    
       - name: Check if make was already run
         stat:
           path: ~/redis_compile/redis-6.2.3/src/redis-cli
         register: compiled
         tags:
          - redis-compile
    
       - name: Run make on ~/redis_compile/redis-6.2.3
         make:
           chdir: ~/redis_compile/redis-6.2.3
         when: compiled.stat.exists == False
         tags:
          - redis-compile
    
       - name: Run make test on ~/redis_compile/redis-6.2.3 (this can take a while)
         make:
           chdir: ~/redis_compile/redis-6.2.3
           target: test
         when: compiled.stat.exists == False
         tags:
          - redis-compile
    
       - name: Create dir for binaries directory
         file:
           path: /usr/local/bin/redis_6.2.3
           state: directory
         tags:
          - redis-dir-bin
    
       - name: Copy binaries
         ansible.builtin.copy:
           src: '{{ item }}'
           dest: /usr/local/bin/redis_6.2.3
           owner: root
           group: root
           mode: '0755'
           backup: yes
           remote_src: yes
         loop:
           - ~/redis_compile/redis-6.2.3/src/redis-cli
           - ~/redis_compile/redis-6.2.3/src/redis-server
           - ~/redis_compile/redis-6.2.3/src/redis-sentinel
         tags:
          - redis-dir-bin
    
       - name: Create env file
         template:
           src: ~/sre-bigdata/redis/ansible/templates/redis_env.j2
           dest: ~/redis_{{ R_MASTER_NAME }}.env
           backup: yes
         tags:
          - tmp2
     tags:
      - setup_common
# /setup_common
# setup_redis
   - name: Setup Redis
     block:

       - name: Check if port {{ R_PORT }} is open. If it is, let's fail and investigate manually.
         shell: ss -ltpn | grep :{{ R_PORT }} | wc -l
         register: open_redis_port
         changed_when: False

       - debug: msg="{{ open_redis_port.stdout }}"
       
       - name: Fail playbook execution if port {{ R_PORT }} is open
         fail:
           msg: Port {{ R_PORT }} is open. Failing, please investigate manually.
         when: open_redis_port.stdout | int > 0

       - name: Create /etc/redis/{{ R_VERSION }}_{{ R_MASTER_NAME }} directory
         file:
           path: /etc/redis/{{ R_VERSION }}_{{ R_MASTER_NAME }}
           state: directory
         tags:
          - redis-etc-dir
    
       - name: Create Redis configuration from template
         template:
           src: ~/sre-bigdata/redis/ansible/templates/6.2.3/redis.conf.j2
           dest: /etc/redis/{{ R_VERSION }}_{{ R_MASTER_NAME }}/{{ R_PORT }}.conf
           backup: yes
         tags:
          - redis-etc-conf
    
       - name: Create Redis init from template (for Redhat)
         template:
           src: ~/sre-bigdata/redis/ansible/templates/6.2.3/redhat_init_redis.j2
           dest: /etc/init.d/redis_{{ R_PORT }}
           backup: yes
         when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'OracleLinux'
         tags:
          - redis-init-redhat
    
       - name: Make Redis init executable (for Redhat)
         ansible.builtin.file:
           path: /etc/init.d/redis_{{ R_PORT }}
           mode: '0755'
         when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'OracleLinux'
         tags:
          - redis-init-redhat

       - name: Create Redis init from template (for Debian)
         template:
           src: ~/sre-bigdata/redis/ansible/templates/6.2.3/debian_init_redis.j2
           dest: /etc/systemd/system/redis_{{ R_PORT }}.service
           backup: yes
         when: ansible_distribution == 'Debian' 
         tags:
          - redis-init-debian
    
       - name: Create /apps/redis/{{ R_VERSION }}_{{ R_MASTER_NAME }}/log directory
         file:
           path: /apps/redis/{{ R_VERSION }}_{{ R_MASTER_NAME }}/log
           state: directory
         tags:
          - redis-apps-dir
    
       - name: Create /apps/redis/{{ R_VERSION }}_{{ R_MASTER_NAME }}/{{ R_PORT }} directory
         file:
           path: /apps/redis/{{ R_VERSION }}_{{ R_MASTER_NAME }}/{{ R_PORT }}
           state: directory
         tags:
          - redis-apps-dir
    
       - name: Enable redis_{{ R_PORT }} service for automatic start
         service:
           name: redis_{{ R_PORT }}
           state: started
           enabled: yes
         tags:
          - redis-autostart
     tags:
      - setup_redis
# /setup_redis
# setup_sentinel
    
   - name: Setup Sentinel
     block:

       - name: Check if port {{ R_SENTINEL_PORT }} is open. If it is, let's fail and investigate manually.
         shell: ss -ltpn | grep :{{ R_SENTINEL_PORT }} | wc -l
         register: open_sentinel_port
         changed_when: False

       - debug: msg="{{ open_sentinel_port.stdout }}"
       
       - name: Fail playbook execution if port {{ R_SENTINEL_PORT }} is open
         fail:
           msg: Port {{ R_SENTINEL_PORT }} is open. Failing, please investigate manually.
         when: open_sentinel_port | int > 0

       - name: Create /etc/redis/sentinel_{{ R_SENTINEL_UNIQUE_STR }}
         file:
           path: /etc/redis/sentinel_{{ R_SENTINEL_UNIQUE_STR }}
           state: directory
         tags:
          - sentinel-etc-dir

       - name: Create /apps/redis/sentinel_{{ R_SENTINEL_UNIQUE_STR }}/log/
         file:
           path: /apps/redis/sentinel_{{ R_SENTINEL_UNIQUE_STR }}/log/
           state: directory
         tags:
          - sentinel-apps-dir

       - name: Create /apps/redis/sentinel_{{ R_SENTINEL_UNIQUE_STR }}/{{ R_SENTINEL_PORT }}
         file:
           path: /apps/redis/sentinel_{{ R_SENTINEL_UNIQUE_STR }}/{{ R_SENTINEL_PORT }}
           state: directory
         tags:
          - sentinel-apps-dir

       - name: Check if Sentinel configuration already exists
         stat:
           path: /etc/redis/sentinel_{{ R_SENTINEL_UNIQUE_STR }}/sentinel_{{ R_SENTINEL_PORT }}.conf
         register: sentinel_config
         tags:
          - sentinel-etc-conf

       - name: Create Sentinel configuration from template /etc/redis/sentinel_{{ R_SENTINEL_UNIQUE_STR }}/sentinel_{{ R_SENTINEL_PORT }}.conf
         template:
           src: ~/sre-bigdata/redis/ansible/templates/6.2.3/sentinel.conf.j2
           dest: /etc/redis/sentinel_{{ R_SENTINEL_UNIQUE_STR }}/sentinel_{{ R_SENTINEL_PORT }}.conf
           backup: yes
         when: sentinel_config.stat.exists == False
         tags:
          - sentinel-etc-conf

       - name: Create Sentinel init.d start/stop script from template (for Redhat)
         template:
           src: ~/sre-bigdata/redis/ansible/templates/6.2.3/redhat_init_sentinel.j2
           dest: /etc/init.d/sentinel_{{ R_SENTINEL_UNIQUE_STR }}
           backup: yes
         when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'OracleLinux'
         tags:
          - sentinel-redhat-init-conf

       - name: Make Sentinel init executable (for Redhat)
         ansible.builtin.file:
           path: /etc/init.d/sentinel_{{ R_SENTINEL_UNIQUE_STR }}
           mode: '0755'
         when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'OracleLinux'
         tags:
          - sentinel-redhat-init-conf

       - name: Create Sentinel init.d start/stop script from template (for Debian)
         template:
           src: ~/sre-bigdata/redis/ansible/templates/6.2.3/debian_init_sentinel.j2
           dest: /etc/systemd/system/sentinel_{{ R_SENTINEL_UNIQUE_STR }}.service
           backup: yes
         when: ansible_distribution == 'Debian'
         tags:
          - sentinel-debian-init-conf
    
       - name: Enable Sentinel sentinel_{{ R_SENTINEL_UNIQUE_STR }} service for automatic start
         service:
           name: sentinel_{{ R_SENTINEL_UNIQUE_STR }}
           state: started
           enabled: yes
         tags:
          - sentinel-autostart
     tags:
      - setup_sentinel
# /setup_sentinel
# configure_master_replica
   - name: On a replica instance tell Redis where is the master
     block:

       - name: Configure a replica on hosts that are not designated master and not replicas already. Checks.
         shell: /usr/local/bin/redis_{{ R_VERSION }}/redis-cli -p {{ R_PORT }} -a {{ R_PASS }} info replication | grep ^role
         register: redis_master_check
         changed_when: False

       - debug: msg="{{ redis_master_check.stdout }}"

       
       - name: Configure a replica on hosts that are not designated master and not replicas already. Running /usr/local/bin/redis_{{ R_VERSION }}/redis-cli -p {{ R_PORT }} -a {{ R_PASS }} replicaof {{ R_MASTER_IP }} {{ R_PORT }}
         shell: /usr/local/bin/redis_{{ R_VERSION }}/redis-cli -p {{ R_PORT }} -a {{ R_PASS }} replicaof {{ R_MASTER_IP }} {{ R_PORT }}
         register: redis_master_action
         when: R_MASTER_IP != ansible_ssh_host and redis_master_check.stdout == "role:master"
       
       - debug: msg="{{ redis_master_action.stdout }}"
         when: redis_master_action.stdout is defined

     tags:
      - configure_master_replica

# /configure_master_replica "
# configure_sentinels
   - name: Configure Sentinel to monitor Redis
     block:

       - name: Check if Sentinel knows already about this Redis.
         shell: cat /etc/redis/sentinel_{{ R_SENTINEL_UNIQUE_STR }}/sentinel_{{ R_SENTINEL_PORT }}.conf | grep {{ R_MASTER_NAME }} | wc -l
         register: sentinel_check
         changed_when: False

       - name: "If below number > 0 that means this Sentinel already has some configuration about this Redis"
         debug: msg="{{ sentinel_check.stdout }}"

       - name: Stop Sentinel sentinel_{{ R_SENTINEL_UNIQUE_STR }} service 
         service:
           name: sentinel_{{ R_SENTINEL_UNIQUE_STR }}
           state: stopped
         tags:
          - configure_sentinels_sentinel_stop
         when: sentinel_check.stdout | int == 0

       - name: Make change in Sentinel configuratio, add Redis to be monitored
         blockinfile: 
           path: /etc/redis/sentinel_{{ R_SENTINEL_UNIQUE_STR }}/sentinel_{{ R_SENTINEL_PORT }}.conf
           block: |
             sentinel monitor {{ R_MASTER_NAME }} {{ R_MASTER_IP }} {{ R_PORT }} 2
             sentinel auth-pass {{ R_MASTER_NAME }} {{ R_PASS }}
             sentinel down-after-milliseconds {{ R_MASTER_NAME }} 30000
             sentinel parallel-syncs {{ R_MASTER_NAME }} 1
             sentinel failover-timeout {{ R_MASTER_NAME }} 180000
           create: no
           state: present
           insertbefore: '# Generated by CONFIG REWRITE'
         when: sentinel_check.stdout | int == 0
 
       - name: Start Sentinel sentinel_{{ R_SENTINEL_UNIQUE_STR }} service 
         service:
           name: sentinel_{{ R_SENTINEL_UNIQUE_STR }}
           state: started
         tags:
          - configure_sentinels_sentinel_start
         when: sentinel_check.stdout | int == 0



     tags:
      - configure_sentinels



# debug
   - name: Display all variables/facts known for a host
     debug:
       var: hostvars[inventory_hostname]
     tags: 
      - debug_info
      - never
