- name: Setup basic actions on computers at home
  hosts: all

  vars_files:
  - ~/_poufne/ansible_vault.yml

  become: yes
  become_user: root
  tasks:
   - name: Install required packages
     apt:
       name: vim
       state: present
     tags:
      - update

   - name: Setup Wi-Fi abrakadabra
     blockinfile:
       path: /etc/wpa_supplicant/wpa_supplicant.conf
       block: |
         network={
           ssid="abrakadabra"
           psk="{{ vault_wifi_abrakadabra }}"
         }
     tags:
      - wifia
      
   - name: Setup hostname
     hostname:
       name: "{{ inventory_hostname }}"
     tags:
      - hostname

   - name: Setup /etc/hosts
     lineinfile:
       dest: /etc/hosts
       regexp: '.*{{ inventory_hostname }}$'
       line: '{{ ansible_ssh_host }} {{ inventory_hostname }}'
       state: present
     tags:
      - hostname

   
   - name: Setup static ip for wlan0
     blockinfile:
       path: /etc/dhcpcd.conf
       block: |
         interface wlan0

         static ip_address={{ ansible_ssh_host }}/24
         static routers=192.168.1.1
         static domain_name_servers=192.168.1.1
     tags:
      - static_ip
