- name: Setup basic actions on computers at home
  hosts: all

  vars_files:
  - ~/_poufne/ansible_vault.yml

  become: yes
  become_user: root
  tasks:
   - name: Install required packages
     apt:
       name: vim
       state: present
     tags:
      - update

   - name: Setup Wi-Fi abrakadabra
     blockinfile:
       path: /etc/wpa_supplicant/wpa_supplicant.conf
       block: |
         network={
           ssid="abrakadabra"
           psk="{{ vault_wifi_abrakadabra }}"
         }
     tags:
      - wifia
      
   - name: Setup hostname
     hostname:
       name: "{{ inventory_hostname }}"
     tags:
      - hostname

   - name: Setup /etc/hosts
     lineinfile:
       dest: /etc/hosts
       regexp: '.*{{ inventory_hostname }}$'
       line: '{{ ansible_ssh_host }} {{ inventory_hostname }}'
       state: present
     tags:
      - hostname

   
   - name: Setup static ip for wlan0
     blockinfile:
       path: /etc/dhcpcd.conf
       block: |
         interface wlan0

         static ip_address={{ ansible_ssh_host }}/24
         static routers=192.168.1.1
         static domain_name_servers=192.168.1.1
     tags:
      - static_ip

   - name: Setup cassandra node, 1. copy jdk
     unarchive:
       src: /KASZTELAN/mirror/utils/jdk-8u191-linux-arm32-vfp-hflt.tar.gz
       dest: /opt
       creates : /opt/jdk1.8.0_191
     tags:
      - cassandra

   - name: Setup cassandra node, 2. copy cassandra binaries
     unarchive:
       src: /KASZTELAN/mirror/utils/apache-cassandra-2.2.13-bin.tar.gz
       dest: /opt
       creates : /opt/apache-cassandra-2.2.13
     tags:
      - cassandra

   - name: Setup cassandra node, 3. update alternative for java
     alternatives:
       name: java
       link: /usr/bin/java
       path: /opt/jdk1.8.0_191/bin/javac
     tags:
      - cassandra

   - name: Setup cassandra node, 4. create a link to /opt/apache-cassandra-2.2.13
     file:
       src: /opt/apache-cassandra-2.2.13
       dest: /opt/cassandra
       owner: root
       group: root
       state: link
     tags:
      - cassandra



   - name: Setup cassandra node, 5a. /opt/cassandra/conf/cassandra.yaml entries removed 1
     lineinfile:
       path: /opt/cassandra/conf/cassandra.yaml
       state: absent
       regexp: '^listen_address: localhost'
     tags:
      - cassandra

   - name: Setup cassandra node, 5b. /opt/cassandra/conf/cassandra.yaml entries removed 2
     lineinfile:
       path: /opt/cassandra/conf/cassandra.yaml
       state: absent
       regexp: '^rpc_address: localhost'
     tags:
      - cassandra

   - name: Setup cassandra node, 6. /opt/cassandra/conf/cassandra.yaml entries added
     blockinfile:
       path: /opt/cassandra/conf/cassandra.yaml
       block: |
         listen_address: {{ ansible_ssh_host }}
         rpc_address: {{ ansible_ssh_host }}
     tags:
      - cassandra


   - name: Setup cassandra node, 7. /opt/cassandra/conf/cassandra.yaml entries replaced
     replace:
       path: /opt/cassandra/conf/cassandra.yaml
       regexp: '          - seeds: "127.0.0.1"'
       replace: '          - seeds: "192.168.1.233,192.168.1.236"'
     tags:
      - cassandra


   - name: Setup cassandra node, 7. /opt/cassandra/conf/cassandra.yaml entries replaced
     replace:
       path: /opt/cassandra/conf/cassandra.yaml
       regexp: '^endpoint_snitch: SimpleSnitch'
       replace: 'endpoint_snitch: GossipingPropertyFileSnitch'
     tags:
      - cassandra


   - name: Setup cassandra node, 8a. /opt/cassandra/conf/cassandra-rackdc.properties entries replaced
     replace:
       path: /opt/cassandra/conf/cassandra-rackdc.properties
       regexp: '^dc=dc1'
       replace: 'dc=SLOWICZA'
     tags:
      - cassandra


   - name: Setup cassandra node, 8b. /opt/cassandra/conf/cassandra-rackdc.properties entries replaced
     replace:
       path: /opt/cassandra/conf/cassandra-rackdc.properties
       regexp: '^rack=rack1'
       replace: 'rack={{ inventory_hostname }}'
     tags:
      - cassandra
