- hosts: all
  become: yes
  become_user: root
  tasks:
   - name: Install required packages
     apt:
       name: apt-transport-https,ca-certificates,curl,software-properties-common,python-pip,python-docker
       state: present
     tags:
      - update

   - name: Add an docker Apt signing key
     apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present
     tags:
      - update

   - name: Add apt repository
     apt_repository:
       repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
       state: present
     tags:
      - update

   - name: Update repositories cache and install "docker-ce" package
     apt:
       name: docker-ce
       update_cache: yes
     tags:
      - update


   - name: Add the user krzysztofk
     user:
       name: krzysztofk
       state: present
       shell: /bin/bash
       groups: adm,sudo
       append: yes
       createhome: yes
     tags:
      - install_and_create_env

   - name: Add the user krzysztofs
     user:
       name: krzysztofs
       state: present
       shell: /bin/bash
       groups: adm,sudo
       append: yes
       createhome: yes
     tags:
      - install_and_create_env

   - name: Add the user maciejz
     user:
       name: maciejz
       state: present
       shell: /bin/bash
       groups: adm,sudo
       append: yes
       createhome: yes
     tags:
      - install_and_create_env

   - name: Add the user maksimb
     user:
       name: maksimb
       state: present
       shell: /bin/bash
       groups: adm,sudo
       append: yes
       createhome: yes
     tags:
      - install_and_create_env

   - name: Set authorized key took from file for krzysztofk
     authorized_key:
       user: krzysztofk
       state: present
       key: "{{ lookup('file', '/opt/devops-test1/public_keys/krzysztof.kokoszka') }}"
     tags:
      - install_and_create_env

   - name: Set authorized key took from file for krzysztofs
     authorized_key:
       user: krzysztofs
       state: present
       key: "{{ lookup('file', '/opt/devops-test1/public_keys/krzysztof.skoracki') }}"
     tags:
      - install_and_create_env

   - name: Set authorized key took from file for maciejz
     authorized_key:
       user: maciejz
       state: present
       key: "{{ lookup('file', '/opt/devops-test1/public_keys/maciej.zasada') }}"
     tags:
      - install_and_create_env

   - name: Set authorized key took from file for maksimb
     authorized_key:
       user: maksimb
       state: present
       key: "{{ lookup('file', '/opt/devops-test1/public_keys/maksim.bachurin') }}"
     tags:
      - install_and_create_env

   - name: Allow 'sudo' group members to have passwordless sudo
     lineinfile:
       dest: /etc/sudoers
       state: present
       regexp: '^%sudo'
       line: '%sudo ALL=(ALL:ALL) NOPASSWD: ALL'
       validate: 'visudo -cf %s'
     tags:
      - install_and_create_env

   - name: Add the user with plain password rysiek
     user:
       name: rysiek
       state: present
       shell: /bin/bash
       createhome: yes
       password: $6$HoZbNFn2Jt61NJqn$4OlgUmcBLUHBBegP4HBwlKbZk6nEwCn7vjBazLgPhgEyxLlFx72Sa8YqAEX.HzSIY7neD4E0Znc9PNU48LYyO/
     tags:
      - install_and_create_env

   - name: git checkout
     git:
       repo: 'https://bitbucket.org/u9/devops-test1.git'
       dest: /opt/devops-test1
     tags:
      - deploy

   - name: Build docker image
     docker_image:
       path: /opt/devops-test1/src
       name: myimage
       buildargs:
         log_volume: /var/log/myapp
         listen_port: 8080
     tags:
      - wip

