version: "2"
services:
  cassandra_node_B1:
    image: remek_cassandra:2.1.19
    restart: "no"
    container_name: cassandra_node_B1
    networks:
      vpcbr:
        ipv4_address: 172.27.0.21
    cap_add:
      - IPC_LOCK
    ulimits:
      nofile: 100000
      nproc: 8192
    volumes:
        - /root/scripto/docker/test_poc/node_B1:/etc/cassandra
        - /var/lib/container_data/cassandra/node_B1/data:/var/lib/cassandra/data
        - /var/lib/container_data/cassandra/node_B1/commitlog:/var/lib/cassandra/commitlog
        - /var/lib/container_data/cassandra/node_B1/log:/var/log/cassandra
        - /root/scripto/docker/test_poc/cqlshrc:/root/.cassandra:ro
        - /var/lib/container_data/backup:/var/lib/cassandra/backup
    environment:
      EXTERNAL_CONFIGURATION: "true"
  cassandra_node_B2:
    image: remek_cassandra:2.1.19
    restart: "no"
    container_name: cassandra_node_B2
    networks:
      vpcbr:
        ipv4_address: 172.27.0.22
    cap_add:
      - IPC_LOCK
    ulimits:
      nofile: 100000
      nproc: 8192
    volumes:
        - /root/scripto/docker/test_poc/node_B2:/etc/cassandra
        - /var/lib/container_data/cassandra/node_B2/data:/var/lib/cassandra/data
        - /var/lib/container_data/cassandra/node_B2/commitlog:/var/lib/cassandra/commitlog
        - /var/lib/container_data/cassandra/node_B2/log:/var/log/cassandra
        - /root/scripto/docker/test_poc/cqlshrc:/root/.cassandra:ro
        - /var/lib/container_data/backup:/var/lib/cassandra/backup
    environment:
      EXTERNAL_CONFIGURATION: "true"
  cassandra_node_B3:
    image: remek_cassandra:2.1.19
    restart: "no"
    container_name: cassandra_node_B3
    networks:
      vpcbr:
        ipv4_address: 172.27.0.23
    cap_add:
      - IPC_LOCK
    ulimits:
      nofile: 100000
      nproc: 8192
    volumes:
        - /root/scripto/docker/test_poc/node_B3:/etc/cassandra
        - /var/lib/container_data/cassandra/node_B3/data:/var/lib/cassandra/data
        - /var/lib/container_data/cassandra/node_B3/commitlog:/var/lib/cassandra/commitlog
        - /var/lib/container_data/cassandra/node_B3/log:/var/log/cassandra
        - /root/scripto/docker/test_poc/cqlshrc:/root/.cassandra:ro
        - /var/lib/container_data/backup:/var/lib/cassandra/backup
    environment:
      EXTERNAL_CONFIGURATION: "true"
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 172.27.0.0/16
         gateway: 172.27.0.2 
