apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    app: bandicoot
    env: staging
    ver: "2"
  name: bandicoot-staging
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/bandicoot-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bandicoot
      env: staging
      ver: "2"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bandicoot
        env: staging
        ver: "2"
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:2
        imagePullPolicy: IfNotPresent
        name: bandicoot-staging
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
