- name: Provision an EC2 Instance
  hosts: local
  connection: local
  gather_facts: False
  tags: provisioning

  tasks:
   - ec2:
       #instance_type: t2.medium
       instance_type: t2.large
       #spot_price: 0.015
       spot_price: 0.035
       spot_wait_timeout: 600
       image: ami-9887c6e7 #CentOS Linux 7 x86_64 HVM EBS
       key_name: nvirginia
       wait: yes
       count: 1
       vpc_subnet_id: subnet-f6b637d9
       group_id: sg-0c48a75e2c61be048
       assign_public_ip: yes
       region: us-east-1
       zone: us-east-1d
       volumes:
         - device_name: /dev/sda1
           volume_type: gp2
           volume_size: 30
           delete_on_termination: true
       instance_tags:
         Name: cloudera

# does not work that below
   - ec2_instance_facts:
       region: "ap-southeast-2"
       filters:
         "tag:Name": A01NANISIM04

     register: ec2_metadata

   - debug: msg="{{ ec2_metadata.instances }}"

   - debug: msg="{{ ec2_metadata.instances[0].public_ip_address }}"
