- name: Provision an EC2 Instance
  hosts: local
  connection: local
  gather_facts: False
  tags: provisioning

  tasks:
   - ec2:
       instance_type: t2.micro
       image: ami-9887c6e7 #CentOS Linux 7 x86_64 HVM EBS
       key_name: nvirginia
       wait: yes
       count: 1
       vpc_subnet_id: subnet-f6b637d9
       group_id: sg-0c48a75e2c61be048
       assign_public_ip: yes
       region: us-east-1
       zone: us-east-1d
       volumes:
         - device_name: /dev/sda1
           volume_type: gp2
           volume_size: 8
           delete_on_termination: true
       instance_tags:
         Name: cloudera
