- name: Build image
  hosts: local
  connection: local
  gather_facts: False
  vars_files:
  - vault.yml

  tasks:
  - name: Stop a container
    docker_container:
      name: phppgadmin
      state: stopped
    ignore_errors: yes

  - name: Build an image and push it to a private repo
    docker_image:
      path: ~/scripto/docker/phppgadmin
      name: unit9_phppgadmin
      tag: latest
      push: no
      force: yes
      buildargs:
        UNIT9_PASS: "{{ phppgadmin.unit9_pass }}"

  - name: start a container
    docker_container:
      name: phppgadmin
      image: unit9_phppgadmin
      state: started
      restart: no
      auto_remove: yes
      exposed_ports:
        - 80

  - name: execute command in docker
    shell: |
      docker exec phppgadmin sh -l -c "cat /tmp/secret"
    register: hello

  - debug: msg="{{ hello.stdout }}"
