- name: Build image
  hosts: local
  connection: local
  gather_facts: False

  tasks:

  - name: Build an image and push it to a private repo
    docker_image:
      path: ~/scripto/docker/phppgadmin
      name: unit9_phppgadmin
      tag: latest
      push: no
